package api

import "strconv"

// defaultCommandRanks mirrors mansionsource-go internal/server/rank_cmds.go DefaultCommandRanks.
// CommandRank: 0=guest, 1=member, 2=wizard, 3=god, 4=owner.
// Keep in sync when the server adds or changes command defaults.
var defaultCommandRanks = map[string]int{
	"help":     0,
	"rev":      0,
	"revision": 0,
	"page":     0,
	"roompage": 0,
	"password": 0,
	"accept":   0,
	"offer":    0,

	"mypic":         1,
	"myroom":        1,
	"mykick":        1,
	"myunkick":      1,
	"mytitle":       1,
	"myowner":       1,
	"myguests":      1,
	"myclose":       1,
	"myopen":        1,
	"myhide":        1,
	"myunhide":      1,
	"mydelete":      1,
	"mypainting":    1,
	"mypassword":    1,
	"regnick":       1,
	"nickpass":      1,
	"nickregister":  1,
	"about":         1,
	"naked":         1,
	"rejectesp":     1,
	"rejectprivate": 1,
	"mute":          1,
	"unmute":        1,
	"mutelist":      1,
	"hide":          1,
	"unhide":        1,
	"hidefrom":      1,
	"unhidefrom":    1,
	"re":            1,
	"respond":       1,
	"death":         1,
	"rname":         1,
	"rpicture":      1,
	"rowner":        1,
	"rkick":         1,
	"runkick":       1,
	"rpassword":     1,
	"rtake":         1,
	"rscripts":      1,
	"rpainting":     1,
	"rguests":       1,
	"rhide":         1,
	"rgag":          1,
	"rungag":        1,

	"give":           2,
	"list":           2,
	"glist":          2,
	"gag":            2,
	"ungag":          2,
	"pin":            2,
	"pinx":           2,
	"unpin":          2,
	"timeout":        2,
	"untimeout":      2,
	"timeoutroom":    2,
	"kill":           2,
	"unkill":         2,
	"ban":            2,
	"unban":          2,
	"uban":           2,
	"banip":          2,
	"banlist":        2,
	"track":          2,
	"trackip":        2,
	"untrack":        2,
	"extend":         2,
	"comment":        2,
	"namegag":        2,
	"move":           2,
	"setcolor":       2,
	"setface":        2,
	"setpos":         2,
	"pdel":           2,
	"clean":          2,
	"props":          2,
	"nolooseprops":   2,
	"propfreeze":     2,
	"purgeprops":     2,
	"newroom":        2,
	"delete":         2,
	"duplicate":      2,
	"close":          2,
	"open":           2,
	"dropzone":       2,
	"uplist":         2,
	"downlist":       2,
	"er":             2,
	"join":           2,
	"rejoin":         2,
	"repage":         2,
	"rmsg":           2,
	"chat":           2,
	"say":            2,
	"esp":            2,
	"notify":         2,
	"roomannotations": 2,
	"ratbot":         1,
	"ratbotsallowed": 2,
	"roombot":        2,
	"uptime":         2,
	"ping":           2,
	"offerall":       2,
	"logout":         2,
	"media":          2,
	"admin":          2,
	"geoip":          2,
	"nicklist":       2,
	"paint":          2,

	"publicmedia":        3,
	"secureprops":        3,
	"unicode":            3,
	"unicodename":        3,
	"altnames":           3,
	"memberrooms":        3,
	"cyborgs":            3,
	"overflow":           3,
	"ypextaddress":       3,
	"ypextport":          3,
	"ypwebsite":          3,
	"yplanguage":         3,
	"ypcategory":         3,
	"ypblurb":            3,
	"ypdescription":      3,
	"servername":         3,
	"maxserverocc":       3,
	"maxocc":             3,
	"maxservocc":         3,
	"defaultroomocc":     3,
	"maxroomocc":         3,
	"roomocc":            3,
	"flush":              3,
	"shutdown":           3,
	"restart":            3,
	"motd":               3,
	"bless":              3,
	"grplst":             3,
	"addgrp":             3,
	"delgrp":             3,
	"addgprv":            3,
	"delgprv":            3,
	"adduprv":            3,
	"deluprv":            3,
	"wizpass":            3,
	"oppass":             3,
	"chatlog":            3,
	"chatlogtype":        3,
	"chatlogformat":      3,
	"floodkill":          3,
	"floodkilltime":      3,
	"floodkillmove":      3,
	"floodkillchat":      3,
	"floodkillwhisper":   3,
	"floodkillesp":       3,
	"floodkillpage":      3,
	"floodkillprop":      3,
	"floodkillpropdrop":  3,
	"floodkilldraw":      3,
	"floodkillusername":  3,
	"soundlimit":         3,
	"deathpenalty":       3,
	"propexpire":         3,
	"autopurge":          3,
	"purgebanlist":       3,
	"autopurgebanlist":   3,
	"purgelimit":         3,
	"purge":              3,
	"nickregistration":   3,
	"registernickgrace":  3,
	"registerednicklist": 3,
	"unregister":         3,
	"regnickmode":        3,
	"regnickforce":       3,
	"regnicklist":        3,
	"regnickadd":         3,
	"regnickdel":         3,
	"upgrade":            3,

	"godpass":           4,
	"ownerpass":         4,
	"rankset":           4,
	"setrank":           4,
	"rankshow":          4,
	"rankclear":         4,
	"mediaupload":       4,
	"mediauploadconfig": 4,
	"legacyclients":     4,
}

// implicitDefaultRank is used for commands not listed in defaultCommandRanks (server uses wizard).
const implicitDefaultRank = 2

func intrinsicDefaultRank(cmd string) int {
	if d, ok := defaultCommandRanks[cmd]; ok {
		return d
	}
	return implicitDefaultRank
}

func rankTierWord(n int) string {
	switch n {
	case 0:
		return "guest"
	case 1:
		return "member"
	case 2:
		return "wizard"
	case 3:
		return "god"
	case 4:
		return "owner"
	default:
		return strconv.Itoa(n)
	}
}
